language: node_js
node_js:
  - "12"
install:
- npm ci
- wget https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.76.5_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo --gc --minify --buildFuture
