sudo: true
dist: trusty

install:
  - sudo apt-get --yes install autoconf libtool nasm
  - npm install
  - wget https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

cache:
  directories:
    - "node_modules"

deploy:
  local-dir: public
  repo: EclipseFdn/iot.eclipse.org
  target-branch: gh-pages
  provider: pages
  keep-history: true
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  email: chris.guindon@eclipse-foundation.org
  name: Christopher Guindon
  on:
    branch: master